# test afterwards
# curl localhost:30080/v1/chat/completions   -H "Content-Type: application/json"   -d '{
#     "model": "meta-llama/Llama-3.1-8B-Instruct",
#     "messages": [
#     {
#         "role": "user",
#         "content": "In the heart of Eldoria, an ancient land of boundless magic and mysterious creatures, lies the long-forgotten city of Aeloria. Once a beacon of knowledge and power, Aeloria was buried beneath the shifting sands of time, lost to the world for centuries. You are an intrepid explorer, known for your unparalleled curiosity and courage, who has stumbled upon an ancient map hinting at ests that Aeloria holds a secret so profound that it has the potential to reshape the very fabric of reality. Your journey will take you through treacherous deserts, enchanted forests, and across perilous mountain ranges. Your Task: Character Background: Develop a detailed background for your character. Describe their motivations for seeking out Aeloria, their skills and weaknesses, and any personal connections to the ancient city or its legends. Are they driven by a quest for knowledge, a search for lost familt clue is hidden."
#     }
#     ],
#     "stream":false,
#     "max_tokens": 30
#   }'

sampleApplication:
  baseConfigMapRefName: basic-gpu-preset
  model:
    modelArtifactURI: hf://meta-llama/Llama-3.1-8B-Instruct
    modelName: "meta-llama/Llama-3.1-8B-Instruct"
  resources:
    limits:
      nvidia.com/gpu: 1
    requests:
      nvidia.com/gpu: 1
  prefill:
    replicas: 0  # Disable prefill for simplicity
  decode:
    replicas: 1
    extraArgs:
      - "--tensor-parallel-size"
      - "1"
      - "--max-model-len"
      - "4096"
      - "--gpu-memory-utilization"
      - "0.7"
      - "--enforce-eager"
      - "--disable-sliding-window"

redis:
  enabled: false

modelservice:
  epp:
    defaultEnvVarsOverride:
      - name: ENABLE_KVCACHE_AWARE_SCORER
        value: "false"
      - name: ENABLE_PREFIX_AWARE_SCORER
        value: "false"
      - name: ENABLE_LOAD_AWARE_SCORER
        value: "false"
      - name: ENABLE_SESSION_AWARE_SCORER
        value: "false"
      - name: PD_ENABLED
        value: "false"