apiVersion: v1
kind: Service
metadata:
  name: rayservice-service
  labels:
    app: rayservice
spec:
  selector:
    ray.io/serve: rayservice-sample
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30080
  type: NodePort
---