name: Test Self-Hosted Runner

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-runner:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show runner info
        run: |
          echo "✅ Running on self-hosted runner!"
          uname -a
          whoami
          echo "Current directory: $(pwd)"

      - name: Create dummy results
        run: |
          mkdir -p benchmark_results
          echo "Hello from self-hosted runner!" > benchmark_results/test_output.txt

      - name: Upload dummy artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: benchmark_results/