name: Test Self-Hosted Runner

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-runner:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show runner info
        run: |
          echo "✅ Running on self-hosted runner!"
          uname -a
          whoami
          echo "Current directory: $(pwd)"

      - name: Check gcloud CLI
        run: |
          echo "✅ Checking gcloud installation..."
          gcloud --version

      - name: Show active gcloud account
        run: |
          echo "✅ Checking gcloud auth list..."
          gcloud auth list

      - name: Show active gcloud project
        run: |
          echo "✅ Checking gcloud active project..."
          gcloud config get-value project

      - name: List Compute Engine instances
        run: |
          echo "✅ Listing compute instances..."
          gcloud compute instances list

      - name: Inject HF_TOKEN into bench-spec.yaml
        shell: bash
        env:
          ENV_HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          if [ -f "bench-spec.yaml" ]; then
            echo "bench-spec.yaml found, injecting HF_TOKEN..."
            if [ -n "$ENV_HF_TOKEN" ]; then
              # Replace hf_token line with secret
              sed -i 's/^\(\s*-*\s*hf_token:\s*\).*/\1'"$ENV_HF_TOKEN"'/' bench-spec.yaml
              echo "Injection complete."
            else
              echo "::warning:: HF_TOKEN secret is not set. Skipping injection."
            fi
          else
            echo "::warning:: bench-spec.yaml not found in project root."
          fi

# TODO:
# run python run-bench.py

# TODO:
# save artifacts (all files ending with .results inside of 4-latest-results/)
  # 1. into a database on this runner (will later host a dashboard on LMCache website)
  # 2. as an artifact for the workflow run (accessible in the UI actions tab)

      - name: Create dummy results
        run: |
          mkdir -p benchmark_results
          echo "Hello from self-hosted runner!" > benchmark_results/test_output.txt

      - name: Upload dummy artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: benchmark_results/
