name: Test Self-Hosted Runner

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-runner:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show runner info
        run: |
          echo "✅ Running on self-hosted runner!"
          uname -a
          whoami
          echo "Current directory: $(pwd)"

      - name: Check gcloud CLI
        run: |
          echo "✅ Checking gcloud installation..."
          gcloud --version

      - name: Show active gcloud account
        run: |
          echo "✅ Checking gcloud auth list..."
          gcloud auth list

      - name: Show active gcloud project
        run: |
          echo "✅ Checking gcloud active project..."
          gcloud config get-value project

      - name: List Compute Engine instances
        run: |
          echo "✅ Listing compute instances..."
          gcloud compute instances list

      - name: Create dummy results
        run: |
          mkdir -p benchmark_results
          echo "Hello from self-hosted runner!" > benchmark_results/test_output.txt

      - name: Upload dummy artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: benchmark_results/
