apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sglang-single
spec:
  serviceName: "sglang-headless"
  replicas: 1
  selector:
    matchLabels:
      app: sglang
  template:
    metadata:
      labels:
        app: sglang
    spec:
      restartPolicy: Always
      containers:
        - name: sglang-container
          image: docker.io/lmsysorg/sglang:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 30000
          command: ["python3", "-m", "sglang.launch_server"]
          args:
            - "--model-path"
            - "MODEL_URL_PLACEHOLDER"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "30000"
            - "--context-length"
            - "32768"
            - "--tensor-parallel-size"
            - "1"
            # optionally:
            # - "--log-requests-level"
            # - "0"
          env:
            - name: HF_TOKEN
              value: <YOUR_HF_TOKEN>
            - name: TRANSFORMERS_CACHE
              value: /huggingface-cache
          resources:
            requests:
              cpu: "10"
              memory: "50Gi"
              nvidia.com/gpu: 1
            limits:
              cpu: "10"
              memory: "50Gi"
              nvidia.com/gpu: 1
          volumeMounts:
            - name: shm
              mountPath: /dev/shm
            - name: hf-cache
              mountPath: /huggingface-cache
          livenessProbe:
            httpGet:
              path: /health
              port: 30000
            initialDelaySeconds: 300
            periodSeconds: 30
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 20Gi
        - name: hf-cache
          persistentVolumeClaim:
            claimName: hf-cache-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sglang-headless
spec:
  selector:
    app: sglang
  clusterIP: None
  ports:
    - name: api
      port: 30000
      targetPort: 30000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hf-cache-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sglang-service
spec:
  selector:
    app: sglang
  ports:
    - name: api
      protocol: TCP
      port: 30000
      targetPort: 30000
  type: LoadBalancer